// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWhwUwEbE9za-gTFpdkeJjw64GO8FL4Jw',
    appId: '1:278429612156:web:7305354b622175bde5b1f9',
    messagingSenderId: '278429612156',
    projectId: 'spices-world',
    authDomain: 'spices-world.firebaseapp.com',
    storageBucket: 'spices-world.appspot.com',
    measurementId: 'G-6P34PHDG47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxMlT5ozKzKgLLz4RycfjrnJS9HrXG1I',
    appId: '1:278429612156:android:32bf5e50c1f0be7fe5b1f9',
    messagingSenderId: '278429612156',
    projectId: 'spices-world',
    storageBucket: 'spices-world.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNZ4YT-7Mvp4ZkacoChprQQoO38tqt3I',
    appId: '1:278429612156:ios:8bb140647497a20ee5b1f9',
    messagingSenderId: '278429612156',
    projectId: 'spices-world',
    storageBucket: 'spices-world.appspot.com',
    iosBundleId: 'com.example.spicesWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwNZ4YT-7Mvp4ZkacoChprQQoO38tqt3I',
    appId: '1:278429612156:ios:66022d1fb3a6d6bde5b1f9',
    messagingSenderId: '278429612156',
    projectId: 'spices-world',
    storageBucket: 'spices-world.appspot.com',
    iosBundleId: 'com.example.spicesWorld.RunnerTests',
  );
}
